### PR TITLE
Fail the take method if the user forgets to provide a count

### PR DESCRIPTION
**Pull request by sunesimonsen**

### CODE REVIEW

**Comment by sunesimonsen** [comment]
@papandreou this should help the situation that you were running into.

**Comment by papandreou** [comment]
Great! Was there another method that just returns the next item?

**Comment by sunesimonsen** [comment]
@papandreou the `take` is just a convenience method for getting an iterator using `values` and take the first `n` items. Do you need a `first` method?

**Comment by sunesimonsen** [comment]
It would probably be useful for debugging.

**Comment by sunesimonsen** [comment]
Adding it now.

**Pull request merged**
