### PR TITLE
Added a first method to the generators

### PR DESCRIPTION
**Pull request by sunesimonsen**
Sometimes I take the "when in doubt leave it out" a bit too far. This is actually useful.

### CODE REVIEW

**Comment by sunesimonsen** [comment]
@papandreou `first` method.

**Comment by sunesimonsen** [comment]
I think I'll rename the method to next instead as the random values actually advances.

**Comment by sunesimonsen** [comment]
I also need to document this feature.

**Comment by sunesimonsen** [comment]
> I think I'll rename the method to next instead as the random values actually advances.

No I'll keep `first` as I think `next` will mislead users to use that instead of creating an iterator.

**Comment by papandreou** [comment]
> I also need to document this feature.

It also seems to be unimplemented :)

```js
const { integer } = require('chance-generators');
const g = integer();
console.log(g.take(1));
console.log(g.first());
```

```
[ -2260084377780223 ]
console.log(g.first());
              ^

TypeError: g.first is not a function
```

**Comment by sunesimonsen** [comment]
> It also seems to be unimplemented :)

It should work, maybe you need to rebuild.

screen shot 2018-11-27 at 22 13 21

**Comment by papandreou** [comment]
Haha, I got lost in the messages floating back and forth here and on gitter, so I didn't realize that this is actually a PR and thought that `first` existed all along :)

I can confirm that it does work if I check out this branch :)

**Comment by papandreou** [comment]
As the PrimitiveGenerator always says: Ej wocu ofaufjom be mabuj do lisib valbuunu bave dolbaw gokim sab.

**Pull request merged**
